# Generated by Django 3.0.8 on 2020-09-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200902_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_edit_books', 'Edit books'),)},
        ),
    ]
