# Generated by Django 3.0.8 on 2020-09-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200902_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_create_copy', 'Create new copy of book'))},
        ),
    ]
